name: BBHuman_Class

on:
  workflow_dispatch:

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: RUN..
        run: |
          zip -r BBHuman_Classv1.2.zip cstrike  # ایجاد فایل zip از دایرکتوری compiled

      - name: Upload BBHuman_Classv1.2.zip
        uses: actions/upload-artifact@v4
        with:
          name: BBHuman_Classv1.2.zip
          path: BBHuman_Classv1.2.zip

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [linux]
    steps:
      - name: Fetch BBHuman_Classv1.2.zip artifact
        uses: actions/download-artifact@v4
        with:
          name: BBHuman_Classv1.2.zip

      - name: Remove old release
        uses: dev-drprasad/delete-tag-and-release@v1.0
        with:
          tag_name: v1.2
          delete_release: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload BBHuman_Classv1.2.zip as release
        uses: svenstaro/upload-release-action@v2
        with:
          file: BBHuman_Classv1.2.zip  # استفاده از فایل compiled.zip برای انتشار
          tag: v1.2
          overwrite: true
          prerelease: False
          release_name: BBHuman_Classv1.2
